name = "cs-homepage"
main = "src/index.js"
compatibility_date = "2024-03-01"

# This section is critical for your images to show up
[assets]
directory = "./public"
binding = "ASSETS"

[observability]
enabled = true