name = "cs-homepage"
main = "src/index.js"
compatibility_date = "2024-03-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "REQUESTS_KV"
id = "requests-kv"
preview_id = "requests-kv-preview"

[observability]
enabled = true

# Production Routes (Only active on 'wrangler deploy')
[[routes]]
pattern = "cs2-homepage.uk"
custom_domain = true

[[routes]]
pattern = "www.cs2-homepage.uk"
custom_domain = true

# --- Preview Environment ---
# Run 'wrangler deploy -e preview' to use this
[env.preview]
name = "cs-homepage-preview"
# We exclude [[routes]] here so it uses the workers.dev URL for testing