name = "cs-homepage"
main = "src/index.js"
compatibility_date = "2024-03-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[env.default.secrets]]
binding = "RESEND_API_KEY"

[[routes]]
pattern = "cs2-homepage.uk"
zone_name = "cs2-homepage.uk"
custom_domain = true

[[routes]]
pattern = "www.cs2-homepage.uk"
zone_name = "cs2-homepage.uk"
custom_domain = true

[observability]
enabled = true