name = "cs-homepage"
main = "src/index.js"
compatibility_date = "2024-03-01"
workers_dev = true
preview_urls = true

[assets]
directory = "./public"
binding = "ASSETS"

[[routes]]
pattern = "cs2-homepage.uk"
zone_name = "cs2-homepage.uk"
custom_domain = true

[[routes]]
pattern = "www.cs2-homepage.uk"
zone_name = "cs2-homepage.uk"
custom_domain = true

[observability]
enabled = true

[env.preview]
name = "cs-homepage-preview"